server:
  port: 9001

spring:
  jpa:
    show-sql: true
    h2:
      console:
        enabled: true
    datasource:
      sql-script-encoding: UTF-8

mes-configs:
    limitDeProduits: 6

management:
  endpoints:
    web:
      exposure:
        include: *