spring:
  application:
    name: microservice-produits
  jpa:
    show-sql: true
    h2:
      console:
        enabled: true
    datasource:
      sql-script-encoding: UTF-8

  mes-configs:
    limitDeProduits: 4

server:
  port: 9002

